name = "plain-limit-3bd8"
type = "webpack"
workers_dev = true
account_id = "c1a654e72c2edae1aac912c06b1af8d6"
zone_id = "8bb4fd88f7fbf679caff2c30616536f7"
kv_namespaces = [
    { binding = "BUCKET", preview_id = "8b5f844a5b1d4f818fa9c29ee6d7f305", id = "e501a423300840e6b8c14ac0ad0d9468" }
]

[env.staging]
name = "plain-limit-3bd8-staging"
